/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkPermissionsRouteImport } from './routes/work-permissions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DoorsRouteImport } from './routes/doors'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DailyAttendanceRouteImport } from './routes/daily-attendance'
import { Route as ComputersRouteImport } from './routes/computers'
import { Route as ComputerActivityRouteImport } from './routes/computer-activity'
import { Route as AttendanceEventsRouteImport } from './routes/attendance-events'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as IndexRouteImport } from './routes/index'

const WorkPermissionsRoute = WorkPermissionsRouteImport.update({
  id: '/work-permissions',
  path: '/work-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsRoute = DoorsRouteImport.update({
  id: '/doors',
  path: '/doors',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyAttendanceRoute = DailyAttendanceRouteImport.update({
  id: '/daily-attendance',
  path: '/daily-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputersRoute = ComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerActivityRoute = ComputerActivityRouteImport.update({
  id: '/computer-activity',
  path: '/computer-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceEventsRoute = AttendanceEventsRouteImport.update({
  id: '/attendance-events',
  path: '/attendance-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance-events': typeof AttendanceEventsRoute
  '/computer-activity': typeof ComputerActivityRoute
  '/computers': typeof ComputersRoute
  '/daily-attendance': typeof DailyAttendanceRoute
  '/departments': typeof DepartmentsRoute
  '/doors': typeof DoorsRoute
  '/employees': typeof EmployeesRoute
  '/positions': typeof PositionsRoute
  '/reports': typeof ReportsRoute
  '/work-permissions': typeof WorkPermissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance-events': typeof AttendanceEventsRoute
  '/computer-activity': typeof ComputerActivityRoute
  '/computers': typeof ComputersRoute
  '/daily-attendance': typeof DailyAttendanceRoute
  '/departments': typeof DepartmentsRoute
  '/doors': typeof DoorsRoute
  '/employees': typeof EmployeesRoute
  '/positions': typeof PositionsRoute
  '/reports': typeof ReportsRoute
  '/work-permissions': typeof WorkPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance-events': typeof AttendanceEventsRoute
  '/computer-activity': typeof ComputerActivityRoute
  '/computers': typeof ComputersRoute
  '/daily-attendance': typeof DailyAttendanceRoute
  '/departments': typeof DepartmentsRoute
  '/doors': typeof DoorsRoute
  '/employees': typeof EmployeesRoute
  '/positions': typeof PositionsRoute
  '/reports': typeof ReportsRoute
  '/work-permissions': typeof WorkPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/analytics'
    | '/attendance-events'
    | '/computer-activity'
    | '/computers'
    | '/daily-attendance'
    | '/departments'
    | '/doors'
    | '/employees'
    | '/positions'
    | '/reports'
    | '/work-permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/analytics'
    | '/attendance-events'
    | '/computer-activity'
    | '/computers'
    | '/daily-attendance'
    | '/departments'
    | '/doors'
    | '/employees'
    | '/positions'
    | '/reports'
    | '/work-permissions'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/analytics'
    | '/attendance-events'
    | '/computer-activity'
    | '/computers'
    | '/daily-attendance'
    | '/departments'
    | '/doors'
    | '/employees'
    | '/positions'
    | '/reports'
    | '/work-permissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceEventsRoute: typeof AttendanceEventsRoute
  ComputerActivityRoute: typeof ComputerActivityRoute
  ComputersRoute: typeof ComputersRoute
  DailyAttendanceRoute: typeof DailyAttendanceRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DoorsRoute: typeof DoorsRoute
  EmployeesRoute: typeof EmployeesRoute
  PositionsRoute: typeof PositionsRoute
  ReportsRoute: typeof ReportsRoute
  WorkPermissionsRoute: typeof WorkPermissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-permissions': {
      id: '/work-permissions'
      path: '/work-permissions'
      fullPath: '/work-permissions'
      preLoaderRoute: typeof WorkPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors': {
      id: '/doors'
      path: '/doors'
      fullPath: '/doors'
      preLoaderRoute: typeof DoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-attendance': {
      id: '/daily-attendance'
      path: '/daily-attendance'
      fullPath: '/daily-attendance'
      preLoaderRoute: typeof DailyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computers': {
      id: '/computers'
      path: '/computers'
      fullPath: '/computers'
      preLoaderRoute: typeof ComputersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-activity': {
      id: '/computer-activity'
      path: '/computer-activity'
      fullPath: '/computer-activity'
      preLoaderRoute: typeof ComputerActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-events': {
      id: '/attendance-events'
      path: '/attendance-events'
      fullPath: '/attendance-events'
      preLoaderRoute: typeof AttendanceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceEventsRoute: AttendanceEventsRoute,
  ComputerActivityRoute: ComputerActivityRoute,
  ComputersRoute: ComputersRoute,
  DailyAttendanceRoute: DailyAttendanceRoute,
  DepartmentsRoute: DepartmentsRoute,
  DoorsRoute: DoorsRoute,
  EmployeesRoute: EmployeesRoute,
  PositionsRoute: PositionsRoute,
  ReportsRoute: ReportsRoute,
  WorkPermissionsRoute: WorkPermissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
